### PR TITLE
Fix set_hvac_mode

### PR DESCRIPTION
**Pull request by nheinemans**
This PR fixes the issue as described in https://github.com/home-assistant/core/issues/84150

### CODE REVIEW

**Comment by MatsNl** [comment]
i've moved to a new house and no longer have access to the device. thats why i havent been active on this repo

**Comment by MatsNl** [comment]
note that this fix wasnt required before. but the api may have changed since my last push

**Comment by nheinemans** [comment]
Thanks for taking the time to get this merged! Do you mind publishing a new version, so I can create a PR to update the component in Home Assistant?

**Comment by MatsNl** [comment]
Done! Hope this fixes the issue, I wasn't able to test it on my end

**Comment by MatsNl** [comment]
i think your fix is actually incorrect. This used to set the device to auto (temperature based) or heat_cool (user controlled). 
if you look closer at the definition of auto hvac mode it is supposed to be this way.

What you probably mean by auto is scheduled. i implemented scheduled as a subset of manual in that sense. i do agree it is confusing they use auto for both automatic mode and scheduled mode. 

consider the definition of auto and especially this part in the below link
```
    # The temperature is set based on a schedule, learned behavior, AI or some
    # other related mechanism. User is not able to adjust the temperature
```
https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py

the reason for the original functionality was to enable the smart mode of the device, which is not the scheduled mode but the outdoor temperature mode

**Comment by nheinemans** [comment]
Maybe I'm missing something, but it looks like hvac_mode is using the ch_mode and preset_mode is using the ch_preset_mode.

I only fixed an issue in the control_mode, it shouldn't affect the hvac_mode.

**Pull request merged**
